### PR TITLE
Fix issues with mciSendString usage

### LINKED ISSUE #25: WINE crash
https://github.com/ayuanx/ogg-winmm/blob/8b18cada757a035b18f48cacb8b7c2294092e1ce/ogg-winmm.c#L256

The wrapper fails when used on Wine for the game Ignition(1997):

9225.700086:0020:0024:Call winmm.mciSendCommandA(0000cdda,00000803,00000000,00000000) ret=639c255a
9225.700091:0020:0024:trace:mci:mciSendCommandA (0000cdda, MCI_OPEN, 00000000, 00000000)
9225.700099:0020:0024:Call ntdll.RtlAllocateHeap(00340000,00000000,00000020) ret=6f24e040
9225.700100:010c:0124:trace:heap:RtlFreeHeap handle 00140000, flags 0, ptr 00797088, return 1, status 0.
9225.700106:010c:0124:Ret  KERNEL32.HeapFree() retval=00000001 ret=684d2ee1
9225.700109:010c:0124:Ret  combase.CoTaskMemFree() retval=00000001 ret=62507cfb
9225.700112:010c:0124:Call KERNEL32.HeapFree(00140000,00000000,00825730) ret=62522cb4
9225.700510:0020:0024:trace:heap:RtlAllocateHeap handle 00340000, flags 0, size 0x20, return 023329E8, status 0.
9225.700516:0020:0024:Ret  ntdll.RtlAllocateHeap() retval=023329e8 ret=6f24e040
9225.700519:0020:0024:trace:mci:mciSendCommandW (0000cdda, MCI_OPEN, 00000000, 023329ec)
9225.700524:0020:0024:trace:mci:MCI_Open (00000000, 023329EC)
9225.700527:0020:0024:fixme:mci:MCI_Open Couldn't load driver
9225.700530:0020:0024:trace:mci:mciSendCommandW => 00000107
9225.700564:0020:0024:trace:seh:dispatch_exception code=c0000005 flags=0 addr=6F24E0ED ip=6f24e0ed
9225.700567:0020:0024:trace:seh:dispatch_exception  info[0]=00000001
9225.700570:0020:0024:trace:seh:dispatch_exception  info[1]=00000004
9225.700586:0020:0024:warn:seh:dispatch_exception EXCEPTION_ACCESS_VIOLATION exception (code=c0000005) raised
[...]
wine: Unhandled page fault on write access to 00000004 at address 6F24E0ED (thread 0024), starting debugger...

Commenting out the relay call fixes this.
Would disabling this relay call depending on a setting from the .ini file be a good fix?

### PR DESCRIPTION
**Pull request by ceclandumitru**
Fixes #25 

Calling `fake_mciSendCommandA(MAGIC_DEVICEID, MCI_OPEN, 0, (DWORD_PTR)NULL);` with the last parameter null causes a crash.

Also add support for MM:SS:FF play format (used by Ignition-1996).

### CODE REVIEW

File: ogg-winmm.c [hunk 1]
```diff
@@ -673,13 +673,17 @@ MCIERROR WINAPI fake_mciSendStringA(LPCSTR cmd, LPSTR ret, UINT cchReturn, HANDL
...
+		fake_mciSendCommandA(MAGIC_DEVICEID, MCI_OPEN, MCI_OPEN_TYPE_ID, (DWORD_PTR)&parms);
 		return 0;
 	}
 
 	if (strstr(cmdbuf, "open cdaudio"))
 	{
-		fake_mciSendCommandA(MAGIC_DEVICEID, MCI_OPEN, 0, (DWORD_PTR)NULL);
+		MCI_OPEN_PARMS parms = {0};
+		parms.wDeviceID = MAGIC_DEVICEID;
+		fake_mciSendCommandA(MAGIC_DEVICEID, MCI_OPEN, MCI_OPEN_TYPE_ID, (DWORD_PTR)&parms);
```
Comment (ayuanx) [inline ogg-winmm.c]: This part doesn't look right.
The correct fix should be commenting out the original line 676 and line 682.

File: ogg-winmm.c [hunk 2]
```diff
@@ -833,6 +833,58 @@ MCIERROR WINAPI fake_mciSendStringA(LPCSTR cmd, LPSTR ret, UINT cchReturn, HANDL
 			notify = 1; /* storing the notify request */
 			window = (HWND)hwndCallback;
 		}
+		
+		// Handle time format (MM:SS:FF) - check these FIRST before integer formats
+		int from_min, from_sec, from_frame, to_min, to_sec, to_frame;
+		if (sscanf(cmdbuf, "play %*s from %d:%d:%d to %d:%d:%d", &from_min, &from_sec, &from_frame, &to_min, &to_sec, &to_frame) == 6)
+		{
+			
+			DWORD from_ms = from_min * 60000 + from_sec * 1000 + from_frame * 1000 / 75;
```
Comment (ayuanx) [inline ogg-winmm.c]: Don't be angry with me, but I think you should check the `time_format` before converting everything to `ms` then converting them back to `MSF`.

If `time_format` is already `MSF`, you should directly convert them to `MSF`.

If `time_format` is not `MSF`, you should return an error.

File: ogg-winmm.c [hunk 3]
```diff
@@ -833,6 +833,58 @@ MCIERROR WINAPI fake_mciSendStringA(LPCSTR cmd, LPSTR ret, UINT cchReturn, HANDL
...
+			DWORD to_ms = to_min * 60000 + to_sec * 1000 + to_frame * 1000 / 75;
+			
+			if (time_format == MCI_FORMAT_MSF) {
+				parms.dwFrom = MCI_MAKE_MSF(from_ms/60000, from_ms/1000%60, from_ms%1000*75/1000);
+				parms.dwTo = MCI_MAKE_MSF(to_ms/60000, to_ms/1000%60, to_ms%1000*75/1000);  
+			} else {
```
Comment (ayuanx) [inline ogg-winmm.c:840]: No need to convert to `ms` in `else`, because there are more than 2 time formats.
When `time_format` is not `MSF`, it doesn't mean it is `ms`, just returning an error would be adequate.

**Review by ayuanx — CHANGES_REQUESTED** [review]

File: ogg-winmm.c (hunk 1 above)
Comment (ceclandumitru) [reply ogg-winmm.c]: It does not hurt either, but sure, I'll comment out these since the call is a NO-OP anyway

File: ogg-winmm.c (hunk 2 above)
Comment (ceclandumitru) [reply ogg-winmm.c]: No trouble, this was anyway copilot-generated late at night without having a clear enough mind to review properly. Just tested to check if it worked properly
